---
- name: Add and remove APT repositories
  hosts: myhosts
  become: true
  become_method: sudo

  tasks:
  - name: Add source repository into sources list
    ansible.builtin.apt_repository:
      repo: deb http://cloud.r-project.org/bin/linux/debian bookworm-cran40/
      state: present
