---
- name: Install web server
  hosts: myhosts
  become: true
  become_method: sudo

  tasks:
  - name: update apt list
    apt:
      update_cache: yes

  - name: Install apache httpd (state=present is optional)
    ansible.builtin.apt:
      name: apache2
      state: present

  - name: Run the equivalent of "apt-get clean" as a separate step
    apt:
      clean: yes
