---
- name: Installs R from APT repo
  hosts: myhosts
  become: true
  become_method: sudo

  tasks:
  - name: update apt list
    apt:
      update_cache: yes

  - name: Install base R
    ansible.builtin.apt:
      name: r-base
      state: present

  - name: Run the equivalent of "apt-get clean" as a separate step
    apt:
      clean: yes
