---
- name: Install RStudio Server
  hosts: myhosts
  become: true
  become_method: sudo

  tasks:
  - name: update apt list
    apt:
      update_cache: yes

  - name: Install gdebi-core
    ansible.builtin.apt:
      name: gdebi-core
      state: present

  - name: Download DEB package
    ansible.builtin.get_url:
      url: https://download2.rstudio.org/server/jammy/amd64/rstudio-server-2023.12.1-402-amd64.deb
      dest: /tmp/rstudio-server-2023.12.1-402-amd64.deb

  - name: Install RStudio Server
    ansible.builtin.command: gdebi --non-interactive /tmp/rstudio-server-2023.12.1-402-amd64.deb
    register: install

  - debug: msg="{{ install.stdout }}"
  - debug: msg="{{ install.stderr }}"

  - name: Remove DEB package
    ansible.builtin.file:
      path: /tmp/rstudio-server-2023.12.1-402-amd64.deb
      state: absent

  - name: Run the equivalent of "apt-get clean" as a separate step
    apt:
      clean: yes
